services:
    sfs_gcloud_integration.logging.client:
        class: Google\Cloud\Logging\LoggingClient

    sfs_gcloud_integration.monolog.formatter:
        class: Monolog\Formatter\LineFormatter
        arguments:
            - "%%channel%%.%%level_name%%: %%message%% %%context%% %%extra%%\n"

